#+TITLE: Chapter 1 Exercises
#+DESCRIPTION: Mathematical Methods in Engineering, Karman and Biot
#+AUTHOR: Jason Ross
#+OPTIONS: toc:nil num:t
#+DATE: 2020-01-09

#+CONTEXT_HEADER: \usemodule[pret-python]
#+CONTEXT_HEADER_EXTRA: \setupdescription[orgdesc][headstyle=bold, style=normal, align=flushleft, alternative=hanging, width=broad, margin=1cm]

* Problem 1
  - Problem :: Evaluate numerically the integral

  \[
  I = \int_0^{\pi/2}{\ln\left(\sin{x}\right) dx}
  \]

  and compare with the exact value $I = -\frac{\pi}{2}\ln{2}$

  - Solution :: ...

    Note that $\ln{\left(\sin x\right)} = \ln{\left(x \frac{\sin x}{x}\right)}
    = \ln{x} + \ln{\frac{\sin x}{x}}$

    Therefore we just need to find
    $\int_0^{\pi/2}{\ln{x} dx}$ analytically and evaluate
    $\int_0^{\pi/2}{\ln{\frac{\sin x}{x}} dx}$ numerically.

    $\int_0^{\pi/2}{\ln{x} dx}$ can be integrated by parts.

    Let $u = \ln x, v^{'} = dx, u^{'} = \frac{1}{x}, v = x$. Therefore,
    $$\int{ln{x} dx} = \int{u v^{'} dx} = u v - \int{v u^{'} dx}$$
    $$ u v - \int{v u^{'} dx} = x \ln x - \int{x \frac{1}{x} dx} = x \ln x - x$$
    And so, $\int_0^{\pi/2}{\ln x dx} = \left. x \ln x - x \right|_0^{\pi/2}$
    \begin{align*}
    \lim_{x \to 0} x \ln x &= \lim_{x \to 0} \frac{\ln x}{\frac{1}{x}}\\
    &= \lim_{x \to 0}-\frac{\frac{1}{x}}{\frac{1}{x^2}}\\
    &= \lim_{x \to 0}-x\\
    &= 0
    \end{align*}
    And, =$\int_0^{\pi/2}{\ln x dx} = \frac{pi}{2} \left(\ln x - 1\right) \approx -0.861$

    #+BEGIN_SRC python :results output code :exports both
    from sympy import log, pi, integrate
    from sympy.abc import x
    print((pi/2 * (log(pi/2) - 1)).evalf())
    print(integrate(log(x), (x, 0, pi/2)).evalf())
    #+END_SRC

    #+RESULTS:
    #+begin_src python
    -0.861451872082119
    -0.861451872082119
    #+end_src

    So we have a value for part of our problem. The other part is to evaluate the integral
    $$\int_0^{\pi/2}{\ln{\frac{\sin x}{x}} dx}$$
    We can do this with Simpson's rule. Recall that
    \[S = \frac{H}{9}\sum_{i=0}^{n-1}{f(x_0 + i H)+
    4 f\left(x_0 + \left(i + \frac{1}{2}\right) H\right) +
    f\left(x_0 + \left(i + 1\right) H\right)}\]
    
    #+BEGIN_SRC python :results output :exports both
    from math import pi, sin, log
    num_points = 10000
    xmin = 0
    xmax = pi/2
    def f(x):
        if x == 0:
            return 0
        return log(sin(x)/x)
    H = (xmax - xmin) / num_points
    def s(x0, i, H, f):
        return H/6 * (
            f(x0 + i * H) 
            + 4 * f(x0 + (i + 1/2) * H) 
            + f(x0 + (i + 1) * H)
        ) 
    print(sum(s(xmin, i, H, f) for i in range(num_points)))
    #+END_SRC
    
    #+RESULTS:
    : -0.2273057071559435
    
    #+BEGIN_SRC python :results file :exports both
    import matplotlib.pyplot as plt
    import numpy as np
    from math import pi, log, sin
    xmin = 0
    xmax = pi/2
    def f(x):
        if x == 0:
            return 0
        return log(sin(x)/x)
    X = np.linspace(xmin, xmax)
    Y = [f(x) for x in X]
    plt.plot(X, Y)
    fname = "myfig.pdf"
    plt.savefig(fname)
    return fname
    #+END_SRC
    
    #+RESULTS:
    [[file:myfig.pdf]]

* Problem 2
  - Problem Statement :: 
    Evaluate numerically the integral $\int_1^2{\frac{dx}{x}}$. Use Simpson's rule with
    an interval $h = 0.1$.
  - Solution :: ...
    #+BEGIN_SRC python :results output :exports both
      from math import log
      import numpy as np
      xmin = 1
      xmax = 2
      h = 0.1
      def f(x):
          return 1/x
      def s(x, h, f):
          return h/3 * (f(x) + 4 * f(x + h) + f(x + 2 * h))
      print(sum(s(x, h, f) for x in np.arange(xmin, xmax - 2 * h, 2 * h)))
    #+END_SRC
    
    #+RESULTS:
    : 0.587789606907254

* Problem 3
  - Problem Statement :: Integrate numerically the differential equation
    \[\frac{dy}{dx} = y\]
    with the initial condition $y = 1$ for $x = 0$. Use Adams' method with
    $h = 1$ in the range from $x = 0$ to $x = 1$.
  - Solution :: ...

    Applying Adams' method, we first compute the Taylor's expansion of the solution
    in the vicinity of $x = 0$. The first derivative is 
    \[\frac{dy}{dx} = y\]
    The second derivative is found by differentiating with respect to $x$:
    \[\frac{d^2y}{dx^2} = \frac{dy}{dx} = y\]
    Differentiating again,
    \[\frac{d^3y}{dx^3} = \frac{d^2y}{dx^2} = y\]
    \[\frac{d^4y}{dx^4} = \frac{d^3y}{dx^3} = y\]
    Using the values of these derivatives at $y=1, x=0$, we find the Taylor's expansion
    \[y = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \frac{x^4}{4!}\]

    #+NAME: adams
    #+BEGIN_SRC python :session adams :output
      def func(x, x0, y0, d0, d1, d2, d3, d4):
          return (
              d0(x0, y0)
              + d1(x0, y0) * (x - x0)
              + d2(x0, y0) * (x - x0)**2 / 2
              + d3(x0, y0) * (x - x0)**3 / 6
              + d4(x0, y0) * (x - x0)**4 / 24
          )
      def get_deltas(l):
          return [lr - ll for lr, ll in zip(l[1:], l[:-1])]
      def get_next_y(y, h, q0, q1, q2, q3, q4):
          return y + h * (q0 + 1/2 * q1 + 5/12 * q2 * 3/8 * q3 + 251/720 * q4)
      epsilon = 1e-10
      def get_values(x0, y0, xmax, h, d0, d1, d2, d3, d4):
          initial_x_vals = [x0 + i * h for i in range(5)]
          initial_y_vals = [func(x, x0, y0, d0, d1, d2, d3, d4) for x in initial_x_vals]
          initial_qs = [d1(x, y) for x, y in zip(initial_x_vals, initial_y_vals)]
          x = initial_x_vals[-1]
          qs = initial_qs
          y_vals = initial_y_vals
          x_vals = initial_x_vals
          while x < xmax - epsilon:
              x += h
              x_vals.append(x)
              dqs = get_deltas(qs)
              ddqs = get_deltas(dqs)
              dddqs = get_deltas(ddqs)
              ddddqs = get_deltas(dddqs)
              next_y = get_next_y(
                  y_vals[-1],
                  h,
                  qs[-1],
                  dqs[-1],
                  ddqs[-1],
                  dddqs[-1],
                  ddddqs[-1]
              )
              qs.append(d1(x, next_y))
      y_vals.append(next_y)
          return y_vals
    #+end_src

    #+results: adams
    now that we've defined a function for adams' method, we can reuse it.

    #+begin_src python :session adams :results output :exports both
      def d0(x, y):
          return y
      def d1(x, y):
          return y
      def d2(x, y):
          return y
      def d3(x, y):
          return y
      def d4(x, y):
          return y
      x0 = 0
      y0 = 1
      h = 0.1
      xmax = 1
      print(*[
          f"{y:.3f}" for y in get_values(x0, y0, xmax, h, d0, d1, d2, d3, d4)
      ])
    #+end_src

    #+results:
    : 1.000 1.105 1.221 1.350 1.492 1.648 1.821 2.011 2.222 2.455 2.712


* Problem 4
  - Problem Statement :: integrate numerically the differential equation
    \[\frac{d^2 y}{dx^2} - x y = 0 \] in the interval between $x = 0$ and $x =
    1$ with the initial conditions $y = 1$ and $\frac{dy}{dx} = 0$ for $x = 0$

  - Solution :: introduce a new unknown variable $u$ by the transformation \[u =
    \frac{1}{y}\frac{dy}{dx}\] or \[u = \frac{d}{dx}\left(\ln y \right)\]
    calculate and substitute $\frac{d^2 y}{dx^2}$; show that the above
    differential equation becomes $\frac{du}{dx} + u^2 - x = 0$ and integrate
    using adams' method using $h = 0.1$.
     \begin{align*}
    \frac{du}{dx} &= -\frac{1}{y^2}\left(\frac{dy}{dx}\right)^2 + \frac{1}{y}\frac{d^2 y}{dx^2} \\
    \frac{d^2 y}{dx^2} &= y \frac{du}{dx} + \frac{1}{y} \left( \frac{dy}{dx} \right)^2 \\
    \frac{d^2 y}{dx^2} - xy &= y \frac{du}{dx} + \frac{1}{y} \left( \frac{dy}{dx} \right)^2 - x y = 0 \\
    \frac{du}{dx} + \left( \frac{1}{y} \frac{dy}{dx} \right)^2 - x &= 0 \\
    \frac{du}{dx} + u^2 - x &= 0
    \end{align*}
    we need to calculate derivatives of $u$ for use in the taylor's series:
    \begin{align*}
    \frac{du}{dx} &= x - u^2 \\
    \frac{d^2 u}{dx^2} &= 1 - 2 u \frac{du}{dx} \\
    &= 1 - 2 x u + 2 u^3 \\
    \frac{d^3 u}{dx^3} &= 2 u + 2 x \frac{du}{dx} + 6 u^2 \frac{du}{dx} \\
    &= 2 u + 2 x^2 - 2 x u^2 + 6 x u^2 - 6 u^4 \\
    &= 2 x^2 + 2 u + 4 x u^2 - 6 u^4 \\
    \frac{d^4}{dx^4} &= 4 x + 2 \frac{du}{dx}
    + 4 u^2 + 8 x u \frac{du}{dx} - 24 u^3 \frac{du}{dx} \\
    &= 4 x + 2 x - 2 u^2 + 4 u^2 + 8 x^2 u - 8 x u^3 - 24 x u^3 + 24 u^5 \\
    &= 6 x + 8 x^2 u + 2 u^2 -32 x u^3 + 24 u^5
    \end{align*}

    #+begin_src python :session adams :results output :exports both
      def d0(x, y):
          return y
      def d1(x, y):
          return x - y**2
      def d2(x, y):
          return 1 - 2 * x * y + 2 * y**3
      def d3(x, y):
          return 2 * x**2 + 2 * y + 4 * x * y**2 - 6 * y**4
      def d4(x, y):
          return 6 * x + 8 * x**2 * y + 2 * y**2 - 32 * x * y**3 + 24 * y**5
      x0 = 0
      y0 = 0
      h = 0.1
      xmax = 1
      u_vals = get_values(x0, y0, xmax, h, d0, d1, d2, d3, d4)
      print(*[
          f"{y:.3f}" for y in u_vals
      ], sep=",")
    #+end_src

    #+results:
    : 0.000,0.005,0.020,0.045,0.080,0.124,0.177,0.238,0.306,0.380,0.458

    let's plot the vector field to get a idea if this is reasonable.


    #+begin_src python :results file :exports both
      import matplotlib.pyplot as plt
      import numpy as np
      x, y = np.meshgrid(np.linspace(0, 1, 25), np.linspace(0, 1, 25))
      def slope(x, y):
          return x - y**2
      u = np.ones_like(x)
      v = slope(x, y)
      plt.figure(figsize=(8, 8))
      plt.quiver(x, y, u, v, scale=30)
      plt.gcf().tight_layout()
      plt.plot( np.linspace(0, 1, 11),
                [0.000,0.005,0.020,0.045,0.080,0.124,0.177,0.238,0.306,0.380,0.458] )
      plt.savefig("temp.pdf")
      return "temp.pdf"

    #+end_src

    #+results:
    [[file:temp.pdf]]

    it remains to apply quadrature to the solution to convert back into a
    differential equation in terms of $y$

* Problem 5
  - Problem statement :: find the general solution of
     \[ \frac{dy}{dx} = \frac{\left(1 + x^2 \right) y^3}{\left( y^2 - 1 \right) x^3} \]
  - Solution :: ...
    this appears to be a separable equation of the form
    \[\frac{dy}{dx} = \frac{\phi(x)}{\psi(y)}\]
    equations of this form can be rewritten as
    \[\psi(y)\frac{dy}{dx} = \phi(x)\]
    which is equivalent to
    \[\frac{d}{dx}\psi(y) = \phi(x)\]
    where $\int{\psi(y) dy} = \psi(y)$ and so this can be rewritten as
    \[\frac{d}{dx}\int_b^y{\psi(y) dy} = \phi(x)\]
    and therefore
    \[\int_b^y{\psi(y) dy} = \int_a^x{\phi(x) dx} \]
    so, letting $\psi(y) = \frac{y^2 - 1}{y^3}$ and $\phi(x) = \frac{1 + x^2}{x^3}$, we can
    solve:
    \[\int_b^y{\frac{y^2 - 1}{y^3} dy} = \int_a^x{\frac{1 + x^2}{x^3} dx}\]
    both sides can be rewritten as the sum of multiple simpler integrals:
    \begin{align*}
    \int_b^y{\frac{y^2 - 1}{y^3} dy} &= \int_b^y{\frac{1}{y} dy} - \int_b^y{y^{-3} dy} \\
    &= \ln{y} + \frac{1}{2 y^2} - \ln{b} - \frac{1}{2 b^2}\\
    \int_a^x{\frac{1 + x^2}{x^3} dx} &= \int_a^x{\frac{1}{x} dx} + \int_a^x{x^{-3} dx} \\
    &= \ln{x} - \frac{1}{2 x^2} - \ln{a} + \frac{1}{2 a^2}
    \end{align*}
    and as a result of this effort we have
    \[\ln{y} + \frac{1}{2 y^2} - \ln{b} - \frac{1}{2 b^2}
    =  \ln{x} - \frac{1}{2 x^2} - \ln{a} + \frac{1}{2 a^2}\]
    which we can simplify, combining constants, to
    \[\ln{\frac{y}{x}} + \frac{1}{2 y^2} + \frac{1}{2 x^2} = c\]
    
* Problem 6
  - Problem statement ::
    find the general solution of
    \[\frac{dy}{dx} = \frac{a^2 + y^2}{2x \sqrt{a x - a^2}}\]
  - Solution ::
    this is a separable equation of the form
    $\frac{dy}{dx} = \frac{\phi(x)}{\psi(y)}$
    where $\phi(x) = \frac{1}{2 x \sqrt{a x - a^2}}$ and
    $\psi(y) = \frac{1}{a^2 + y^2}$.
    the above equation can then be rewritten as
    \[\psi(y)\frac{dy}{dx} = \phi(x)\]
    letting $\psi(y) = \int{\psi(y) dy}$ we see that
    $\frac{d}{dx}\psi(y) = \psi(y)\frac{dy}{dx}$, so we can rewrite again as
    \begin{align*}
    \frac{d}{dx}\psi(y) &= \phi(x)\\
    \frac{d}{dx}\int{\psi(y)dy} &= \phi(x)\\
    \int{\psi(y) dy} &= \int{\phi(x) dx}
    \end{align*}
    substituting in our values for $\psi(y), \phi(x)$, we have
    \[\int_{y_0}^y{\frac{1}{a^2 + y^2} dy} = \int_{x_0}^x{\frac{1}{2 x \sqrt{a
    x - a^2}} dx}\]
    carrying out the integration on the left side, letting
    $u = \frac{y}{a}, du = \frac{dy}{a}$ we have
    \begin{align*}
    \int{\frac{1}{a^2 + y^2} dy} &=
    \int{\frac{a}{a^2 + a^2 u^2}du}\\
    &= \frac{1}{a}\int{\frac{1}{1 + u^2}du}\\
    &= \frac{1}{a}\arctan{u} \\
    &= \frac{1}{a}\arctan{\frac{y}{a}}
    \end{align*}
    carrying out the integration on the right side, letting
    \begin{align*}
    u &= \sqrt{a x - a^2}\\
    du &= -\frac{a}{2\sqrt{a x - a^2}} dx\\
    dx &= -\frac{2\sqrt{a x - a^2}}{a} du\\
    &= -\frac{2 u}{a} du \\
    x &= \frac{u^2 + a^2}{a}
    \end{align*}
    we have
    \begin{align*}
    \int{\frac{1}{2 x \sqrt{a x - a^2}} dx} &=
    - \int{\frac{1}{2 \frac{u^2 + a^2}{a} u}\frac{2 u}{a} du }\\
    &= \int{\frac{1}{u^2 + a^2} du}
    \end{align*}
    we can now perform a second substitution, letting $v = \frac{u}{a}, dv = \frac{du}{a}$
    which gives $u = v a, du = dv a$
    \begin{align*}
    \int{\frac{1}{u^2 + a^2} du} &= a \int{\frac{1}{a^2 + a^2 v^2} dv} \\
    &= \frac{1}{a}\int{\frac{1}{1 + v^2} dv}\\
    &= \frac{1}{a} \arctan{v} \\
    &= \frac{1}{a} \arctan{\frac{u}{a}} \\
    &= \frac{1}{a} \arctan{\frac{\sqrt{a x - a^2}}{a}} \\
    \end{align*}
    inserting our results back into our original expression, we have

    \begin{align*}
    \frac{1}{a}\arctan{\frac{y}{a}} &= \frac{1}{a}\arctan{\frac{\sqrt{a x - a^2}}{a}} + c \\
    \arctan{\frac{y}{a}} &= \arctan{\frac{\sqrt{a x - a^2}}{a}} + c
    \end{align*}

* Problem 7
  - Problem statement ::
    find the family of curves which cut at right angles the parabolas given by
    \[y^2  = 2 p (x - a) \]
  - Solution :: ...
    we seek a family of curves such that the derivative of the curve is equal to the
    negative of the reciprocal of the derivative of the given parabola.
    the slope of the given parabola is found by
    \begin{align*}
    x &= \frac{y^2}{2 p} + a \\
    \frac{dx}{dy} &= \frac{y}{p}
    \end{align*}
    the differential equation for our solution is given by
    \begin{align*}
    \frac{dx}{dy} = -\frac{p}{y}
    \end{align*}
    we can integrate both sides of this equation with respect to y:
    \begin{align*}
    x &= -p \int{\frac{1}{y} dy} \\
    x &= -p \ln{y} + c \\
    \end{align*}
* Problem 8
  - Problem statement ::
    find the general solution of the differential equation
    \[x^2 \frac{dy}{dx} = x^2 + y^2 \]
  - Solution ::
    this equation can be rewritten in the form of a homogeneous equation:
    \[\frac{dy}{dx} = 1 + \left(\frac{y}{x}\right)^2 = f\left(\frac{y}{x}\right)\]
    letting $u = \frac{y}{x}; y = x u$ we have by differentiating
    \[\frac{dy}{dx} = u + x \frac{du}{dx} \]
    and therefore our previous equation becomes 
    \[ \frac{du}{dx} = \frac{f\left(u \right) - u}{x} \]
    this is now a separable equation in $u$ and $x$. rewriting it with the usual
    abuse of notation, we have
    \[ \frac{du}{f(u) - u} = \frac{dx}{x} \]
    and by integration
    \[ \int{\frac{du}{f(u) - u}}  = \int{\frac{dx}{x}} \]
    then the right hand side becomes $\log{x} + c$ and the left hand side depends on
    our particular $f(u)$.
    in this case, $f(u) = 1 + u^2$ and so the left hand side becomes
    \[ \int{\frac{du}{u^2 - u + 1}} \]
    we can complete the square in the denominator:
    \[ u^2 - u + 1 = \left (u - \frac{1}{2} \right )^2 + \frac{3}{4} \]
    and therefore, letting $v = \frac{2\sqrt{3}}{3} \left(u - \frac{1}{2} \right), dv = \frac{2 \sqrt{3}}{3}du$,
    we have on the left hand side
    \begin{align*}
    \frac{\sqrt{3}}{2}\int{\frac{dv}{3/4 v^2 + 3/4}} & \\
    &= \frac{2\sqrt{3}}{3}\int{\frac{dv}{v^2 + 1}} \\
    &= \frac{2\sqrt{3}}{3}\arctan{v} \\
    &= \frac{2\sqrt{3}}{3}\arctan{\left(\frac{2\sqrt{3}}{3} \left(u - \frac{1}{2} \right) \right)} \\
    &= \frac{2\sqrt{3}}{3}\arctan{\left(\frac{2\sqrt{3}}{3} \left(\frac{y}{x} - \frac{1}{2} \right) \right)} \\
    \end{align*}
    and so, with our right hand side from before, we have
    \begin{align*}
    \log{x} + c &= \frac{2\sqrt{3}}{3}\arctan{\left(\frac{2\sqrt{3}}{3} \left(\frac{y}{x} - \frac{1}{2} \right) \right)} \\
    \frac{\sqrt{3}}{2}\log{x} + c &= \arctan{\left(\frac{2\sqrt{3}}{3} \left(\frac{y}{x} - \frac{1}{2} \right) \right)} \\
    \tan{\left(\frac{\sqrt{3}}{2}\log{x} + c \right)} &= \frac{2\sqrt{3}}{3} \left(\frac{y}{x} - \frac{1}{2} \right) \\
    \frac{\sqrt{3}}{2}\tan{\left(\frac{\sqrt{3}}{2}\log{x} + c \right)} + \frac{1}{2} &= \frac{y}{x} \\
    x \left[ \frac{\sqrt{3}}{2}\tan{\left(\frac{\sqrt{3}}{2}\log{x} + c \right)} + \frac{1}{2} \right] &= y \\
    \end{align*}
* Problem 9
  - Problem Statement ::
    find the general solution of the differential equations:
    \begin{align}
    \frac{d^4y}{dx^4} + y &= 0 \\
    \frac{d^4y}{dx^4} - y &= 0 
    \end{align}
  - Solution :: because these are both linear ordinary differential equations, we can solve
    by assuming a solution of the form $y = e ^ {a x}$. substituting this into
    the equations will yield a polynomial in $a$ which we can solve for algebraically.
  - Solution 1 ::
    \[ \frac{d^4 y}{dx^4} + y = 0 \]
    let $y = e ^ {a x}$. therefore, we have
    \begin{align*}
    \frac{d^4}{dx^4} e^{a x} + e^{a x} &= 0 \\
    a^4 e^{a x} + e^{a x} &= 0 \\
    a^4 + 1 &= 0 \\
    a^4 &= -1 \\
    \end{align*}
    so we're looking $a$ such that $a^4 = -1$. this is satisfied when $a^2 = \pm i$
    or when $a = \pm \sqrt{\frac{1}{2}} \pm i \sqrt{\frac{1}{2}}$.
    \begin{align*}
    proof. \\
    \left( \sqrt{\frac{1}{2}} + i \sqrt{\frac{1}{2}} \right) ^2 &= \frac{1}{2} + 2 \frac{1}{2} i + \frac{1}{2} i^2 = i \\
    \left( \sqrt{\frac{1}{2}} - i \sqrt{\frac{1}{2}} \right) ^2 &= \frac{1}{2} - 2 \frac{1}{2} i + \frac{1}{2} i^2 = -i \\
    \left( -\sqrt{\frac{1}{2}} + i \sqrt{\frac{1}{2}} \right) ^2 &= \frac{1}{2} - 2 \frac{1}{2} i + \frac{1}{2} i^2 = -i \\
    \left( -\sqrt{\frac{1}{2}} - i \sqrt{\frac{1}{2}} \right) ^2 &= \frac{1}{2} + 2 \frac{1}{2} i + \frac{1}{2} i^2 = i \\
    \end{align*}
    so our final solution is
    \begin{align*}
    & c_1 e^{\sqrt{1/2} \left( 1 + i \right) x}
    + c_2 e^{\sqrt{1/2} \left( 1 - i \right) x}
    + c_3 e^{\sqrt{1/2} \left( -1 + i \right) x}
    + c_4 e^{\sqrt{1/2} \left( -1 - i \right) x} \\
    &= c_1 e^{\sqrt{1/2} x} \left( \cos{ \left( \sqrt{1/2} x \right) } + i \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    &\quad + c_2 e^{\sqrt{1/2} x} \left( \cos{ \left( \sqrt{1/2} x \right) } - i \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    &\quad + c_3 e^{-\sqrt{1/2} x} \left( \cos{ \left( \sqrt{1/2} x \right) } + i \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    &\quad + c_4 e^{-\sqrt{1/2} x} \left( \cos{ \left( \sqrt{1/2} x \right) } - i \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    \end{align*}
    or, combining arbitrary constants,

    \begin{align*}
    e^{\sqrt{1/2} x} \left( c_1 \cos{ \left( \sqrt{1/2} x \right) } + c_2 \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    + e^{-\sqrt{1/2} x} \left( c_3 \cos{ \left( \sqrt{1/2} x \right) } + c_4 \sin{ \left( \sqrt{1/2} x \right) } \right) \\
    \end{align*}
  - Solution 2 :: 
    \[ \frac{d^4 y}{dx^4} - y = 0 \]
    let $y = e ^ {a x}$. therefore, we have
    \begin{align*}
    \frac{d^4}{dx^4} e^{a x} - e^{a x} &= 0 \\
    a^4 e^{a x} - e^{a x} &= 0 \\
    a^4 - 1 &= 0 \\
    a^4 &= 1 \\
    \end{align*}
    so we're looking $a$ such that $a^4 = -1$. this is satisfied when $a^2 = \pm 1$
    or when $a = 1, a = -1, a = i, a = -i$.
    this gives us
    \[ y = c_1 e^{x} + c_2 e^{-x} + c_3 e^{i x} + c_4 e^{-i x} \]
    applying euler's identity to this gives us
    \[ y = c_1 e^{x} + c_2 e^{-x} + c_3 \left( \cos{x} + i \sin{x} \right) + c_4 \left( \cos{x} - i \sin{x} \right) \]
    we can combine constants to get
    \[ y = c_1 e^{x} + c_2 e^{-x} + c_3 \cos{x} + c_4 \sin{x} \]
* Problem 10
  - Problem statement ::
    find the general solution of the following differential equations:
    \begin{align}
    \frac{dy}{dx} + y \cos x &= \sin x \cos x \\
    \frac{dy}{dx} &= \frac{n y}{x + 1} + e^x \left( x + 1 \right) ^n
    \end{align}
  - Solution 1 ::
    this is a linear differential equation of the first order of the form
    \[\frac{dy}{dx} = \phi(x) y + \psi(x) \]
    we can solve this by substituting $y = u v$.
    then,
    \[\frac{dy}{dx} = u \frac{dv}{dx} + v \frac{du}{dx} \]
    applying this to the general form of problem, we have
    \[ u \frac{dv}{dx} + v \frac{du}{dx} = \phi(x) y + \psi(x) \]
    or in particular,
    \[ u \frac{dv}{dx} + v \frac{du}{dx} = -y \cos x + \sin x \cos x \]
    let us choose $v$ such that $u \frac{dv}{dx} = \phi(x) uv$ or
    $\frac{1}{v} \frac{dv}{dx} = \phi(x)$ which is a separable
    differential equation and is solved thus:
    \begin{align*}
    \frac{1}{v} \frac{dv}{dx} &= \phi(x) \\
    \int{\frac{1}{v} dv} &= \int{\phi(x) dx} \\
    \log{v} &= \int{\phi(x) dx} \\
    v &= e^{\int{\phi(x) dx}}
    \end{align*}
    we can substitute this expression into our original general differential equation
    given our choice for $v$:
    \begin{align*}
    v \frac{du}{dx} &= \psi(x) \\
    \frac{du}{dx} &= \frac{\psi(x)}{v} \\
    \frac{du}{dx} &=    e^{-\int{\phi(x) dx}} \psi(x) \\
    u &= \int_0^x{e^{-\int_0^x{\phi(x) dx}} \psi(x) dx} \\
    y &= e^{\int_0^x{\phi(x) dx}} \int_0^x{e^{-\int_0^x{\phi(x) dx}} \psi(x) dx} \\
    or \\
    y &= v \int_0^x{\frac{\psi(x)}{v}dx}
    \end{align*}
    from the original problem statement, we have $\phi(x) = -\cos{x}$. thus,
    \begin{align*}
    v &= e^{\int{\phi(x) dx}} \\
    &= e^{\int{-\cos x dx}} \\
    &= e^{- \sin x }
    \end{align*}
    substituting the value for $v$ back into the problem statement we have
    \begin{align*}
    y &= e^{- \sin x} \int_0^x{e^{\sin x} \sin x \cos x dx}
    \end{align*}
    this can be integrated by parts.
    letting
    \begin{align*}
    u &= \sin{x} \\
    v^{'} &= e^{\sin x} \sin x \\
    v &= e^{\sin x} \\
    u^{'} &= \cos{x} \\
    \int{u v^{'}} &= u v - \int{u^{'} v} \\
    &= \sin{(x)} e^{\sin x} - \int{\cos{x} e^{\sin x} dx}
    \end{align*}
    this second part can be integrated by making a substitution, letting
    $u = \sin x, du = \cos x dx$ yields
    \begin{align*}
    \int{\cos{x} e^{\sin x} dx} &= \int{e^u du} \\
    &= e^u \\
    &= e^{\sin x}
    \end{align*}
    this gives us a result of
    \[ \sin{(x)} e^{\sin x} - e^{\sin x} \]

    combining this result with our previous result we are left with
    \begin{align*}
    y &= e^{-\sin x} \left( \sin{(x)} e^{\sin x} - e^{\sin x} \right) \\
    &= \sin x - 1
    \end{align*}

    checking our work, we have
    \begin{align*}
    \frac{dy}{dx} &= \cos x \\
    \frac{dy}{dx} + y \cos x &= \cos x + \sin x \cos x - \cos x \\
    &= \sin x \cos x
    \end{align*}
  - solution 2 ::
    \[ \frac{dy}{dx} = \frac{n y}{x + 1} + e^x \left( x + 1 \right) ^n \]

    this is an equation of the form
    \[ \frac{dy}{dx} = \phi(x) y + \psi(x) \]
    let $u(x), v(x)$ such that $y = u v$, we then have
    \[ \frac{dy}{dx} = \frac{d}{dx} u(x) v(x) = u \frac{dv}{dx} + v \frac{du}{dx} \]
    and therefore
    \[ u \frac{dv}{dx} + v \frac{du}{dx} = \phi(x) y + \psi(x) \]
    we can arbitrarily choose that
    \[ v \frac{du}{dx} = \phi(x) u v \]
    so that
    \[ \frac{1}{u} du = \phi(x) dx \]
    and thus
    \[ \log u = \int{\phi(x) dx} \]
    or
    \[ u = e ^ {\int{\phi(x)} dx } \]
    given our value for $u$, we can return to our problem and find v:
    \begin{align*}
    u \frac{dv}{dx} &= \psi(x) \\
    \frac{dv}{dx} &= \frac{\psi(x)}{u} \\
    \frac{dv}{dx} &= \psi(x) e ^ { - \int{\phi(x)} dx } \\
    v &= \int{ \psi(x) e ^ { - \int{\phi(x)} dx } dx }
    \end{align*}
    back to our problem, we have
    \begin{align*}
    \phi(x) &= \frac{n}{x + 1} \\
    \psi(x) &= e^x \left( x + 1 \right) ^n \\
    u &= e ^ {\int{\frac{n}{x + 1}}}
    \end{align*}
    we need to integrate $\int{\frac{n}{x + 1} dx}$. this will be done with a
    $u$ substitution letting $u = x + 1, du = dx$. this gives
    \[ \int{\frac{n}{x + 1}} = n \log u = n \log{(x + 1)} \]
    so
    \begin{align*}
    u &= e ^ {n \log{(x + 1)} }\\
    &= \left( e^{\log{(x + 1)}} \right) ^ n \\
    &= (x + 1)^n \\
    e^ { - \int {\phi(x) dx} } &= e ^ {-n \log{(x + 1)} } \\
    &= (x + 1)^ {-n} \\
    v &= \int{ \psi(x)e^ { - \int {\phi(x) dx} }  dx } \\
    &= \int{ e^x (x + 1) ^n (x + 1) ^{-n} dx } \\
    &= \int{ e^x  } \\
    &= e^x \\
    y &= e^x (x + 1)^n
    \end{align*}
    we can check our solution:
    \begin{align*}
    \frac{dy}{dx} &= \frac{d}{dx} \left( e^x (x + 1)^n \right) \\
    &= e^x (x + 1) ^n + n e^x (x + 1) ^ {n - 1} \\
    \frac{n y}{x + 1} + e^x (x + 1) ^n &= \frac{n e^x (x + 1)^n} {x + 1} + e^x (x + 1)^n \\
    &= n e^x (x + 1) ^ {n - 1} e^x (x + 1)^n
    \end{align*}
* TODO Problem 11
  - Problem Statement ::
    a constant voltage $e$ i applied to a resistance at the time $t = 0$. the heat
    capacity of the resistance is $q$, its heat transfer coefficient per unit time
    and unit surface is $\alpha$, and its surface area is $s$. the resistance as a
    function of temperature is given by
    \[ r = r_0 (1 + \beta \theta) \]
    where $\theta$ is the temperature of the resistance above room temperature. find
    a relation between temperature $\theta$ and time.
  - Solution ::
    we find a differential equation for the temperature by expressing the fact that
    the heat produced per second by the current is partly stored in the resistance
    and partly lost by transfer through the surface. the equation of heat balance
    is $\frac{e^2}{1 + \beta \theta} - \alpha s \theta = q \frac{d\theta}{dt}$. the final
    temperature $\theta_f$ must correspond to $\frac{d\theta}{dt} = 0$, hence it is
    given by $\frac{e^2}{r_0 (1 + \beta \theta_f)} = \alpha s \theta_f$. introducing
    the dimensionless variable $\eta = \frac{\theta}{\theta_f}$, we can rewrite the
    differential equation as $\frac{q}{\alpha s} \frac{d\eta}{dt} = \frac{1 + \beta \theta_f}
    {1 + \beta \theta_f \eta} - \eta$.

    given the dimensionless equation, let's try substituting $u = \frac{1}{\eta}$.
    \begin{align*}
    \eta &= \frac{1}{u} \\
    \frac{d \eta}{dt} &= \frac{d}{dt} \frac{1}{u} \\
    &= -\frac{1}{u^2} \frac{du}{dt}
    \end{align*}
    let $\gamma = \frac{q}{\alpha s}$ and $\xi = \beta \theta_f$. then,
    \begin{align*}
    -\gamma \frac{1}{u^2} \frac{du}{dt} &= \frac{1 + \xi}{1 + \frac{\xi}{u}} - \frac{1}{u} \\
    -\gamma \frac{du}{dt} &= u^2 \frac{1 + \xi}{1 + \frac{\xi}{u}} - u \\
    &= u^2 \frac{1 + \xi}{1 + \frac{\xi}{u}} - u \\
    \end{align*}

    that doesn't work at all!

    maybe we're overcomplicating this.
    \[ \frac{q}{\alpha s} \frac{d\eta}{dt} = \frac{1 + \beta \theta_f}
    {1 + \beta \theta_f \eta} - \eta \]

    this looks like it could be separable! maybe i can just flip the sides around
    and integrate.

    \[ \frac{q}{\alpha s} \frac{1} {\frac{1 + \beta \theta_f}
    {1 + \beta \theta_f \eta} - \eta} d\eta = dt \]

    this is an ugly fraction but so be it. here we go!

    \[ \frac{1 + \beta \theta_f \eta} { 1 + \beta \theta_f - \eta - \beta \theta_f \eta^2} d\eta
    = \frac{\alpha s}{q} dt \]

    now we just need to suffer through integrating both sides. we have to complete the
    square.

    \begin{align*}
    1 + \beta \theta_f - \eta - \beta \theta_f \eta^2 &= -
    \beta \theta_f \left( \eta^2 + \frac{\eta}{\beta \theta_f}  -
    \frac{1} {\beta \theta_f} - 1 \right) \\
    \eta^2 + \frac{\eta}{\beta \theta_f}  -
    \frac{1} {\beta \theta_f} - 1 
    &= \left( \eta + \frac{ 1 }{ 2 \beta \theta_f } \right) ^2
    - \frac{ 1 }{ \beta \theta_f } - 1 - \left( \frac{ 1 }{ 2 \beta \theta_f } \right) ^2 
    \end{align*}

    This is nice. Let $a$ be the stuff outside the parentheses and $u$ be the
    stuff inside the parentheses. We then have an integral of the form
    $\frac{1 + k u}{ u^2 - a^2}$, which can be split up into two parts:
    $\int{\frac{1}{u^2 - a^2} du}$ and $\int{\frac{u}{u^2 - a^2}}$. The first part
    evaluates to $\frac{1}{2a} \log{ \left( \frac{x - a}{x + a} \right) }$ (from
    a table), and the second can be solved with a $u$ substitution.

    Let's figure out
    $$\int{\frac{u }{u^2 - a^2 } du}$$
    Let $v = u^2 - a^2$, $dv = 2u du$. Thus,
    \begin{align*}
    \int{\frac{u }{u^2 - a^2 } du} &= \frac{1}{2} \int{ \frac{ 1 }{ v } dv} \\
    &= \frac{ 1 }{ 2 } \log{ v } \\
    &= \frac{ 1 }{ 2 } \log{ \left( u^2 - a^2 \right) }
    \end{align*}

    Returning back to our original problem, we need to manipulate the integrand
    into the form $\frac{1 + k u}{ u^2 - a^2}$.

    \begin{align*}
    u &= \eta + \frac{ 1 }{ 2 \beta \theta_f } \\
    du &= d\eta \\
    \eta &= u - \frac{ 1 }{ 2 \beta \theta_f } \\
    a &= 1 + \frac{ 1 }{ \beta \theta_f } + \left( \frac{ 1 }{ 2 \beta \theta_f } \right) \\
    \frac{1 + \beta \theta_f \eta} { 1 + \beta \theta_f - \eta - \beta \theta_f \eta^2} 
    &= -\frac{ 1 }{ \beta \theta_f } \frac{ 1 + \beta \theta_f
    \left( u - \frac{ 1 }{ 2 \beta \theta_f } \right) }{ u^2 - a^2} \\
    &= -\frac{ 1 }{ \beta \theta_f } \frac{
    1 + \beta \theta_f u - \frac{ 1 }{ 2 } }{ u^2 - a^2} \\
    &= -\frac{ 1 }{ 2 \beta \theta_f } \frac{ 1 }{ u^2 - a^2 }
    - \frac{ u }{ u^2 - a^2 } \\
    \int{- \frac{ 1 }{ 2 \beta \theta_f } \frac{ 1 }{ u^2 - a^2 }
    - \frac{ u }{ u^2 - a^2 }}du &=
    - \frac{ 1 }{ 4 \beta \theta_f } \log{ \left( u^2 - a^2 \right) }
    - \frac{ 1 }{ 2 a } \log{ \left( \frac{ x - a }{ x + a } \right) }
    \end{align*}
* TODO Problem 12
  The pressure distribution $p(x)$ in the oil fil between the inclined
  surface $S_a$ which moves with the velocity $U$ and the fixed base $S_2$
  is given by the equation
  $$\frac{ dp }{ dx } = \frac{ 12 \mu }{ h^3 } \left( Q - \frac{ U h }{ 2}
  \right)$$
* TODO Problem 13
* TODO Problem 14
* TODO Problem 15
* TODO Problem 16
* Problem 17
  - Problem Statement ::
    Expand the function $y = \cosh^5 x$ as a series of hyperbolic cosines.
  - Solution ::
    Rewrite $\cosh x$ as $\frac{ e^x + e^{-x} }{ 2 }$. Therefore, we can
    write $\cosh^5 x$ as
    \begin{align*}
    & \frac{ 1 }{ 32 } \left( e^x + e^{ -x } \right) \\
    &= \frac{ 1 }{ 32 } \left( e^{5x} + 5 e^{4x} e^{-x}
    + 10 e^{3x} e^{-2x} + 10 e^{2x} e{-3x} + 5 e^{x} e^{-4x}
    + e^{-5x} \right) \\
    &= \frac{ 1 }{ 32 } \left( e^{5x} + 5 e^{3x} + 10 e^{x}
    + 10 e^{-x} + 5 e^{-3x} + e^{-5x} \right) \\
    &= \frac{ 1 }{ 32 } \left( 2 \cosh{5x} + 10 \cosh{3x}
    + 20 \cosh{x} \right) \\
    &= \frac{5}{8} \cosh{x} ++ \frac{5}{16} \cosh{3x} + \frac{1}{16}\cosh{5x}
    \end{align*}

