# Copyright (C) 2021 Jason Ross
# Author: Jason Ross <jasonross1024 at gmail dot com>

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
 

#+TITLE: Org Mode ConTeXt Export Demo
#+DESCRIPTION: Simple demo of the Org Mode ConTeXt exporter
#+KEYWORDS: context org-mode
#+SUBTITLE: Sampling of Features
#+AUTHOR: Jason Ross
#+EMAIL: jasonross1024@gmail.com
#+CREATOR: Jason Ross
#+LANGUAGE: en
#+OPTIONS: foldmarks:nil toc:t backaddress:t pri:t p:t c:t prop:t d:t ':t
#+CONTEXT_PRESET: article
#+DATE: 2021-01-07

List of Tables
#+TOC: tables
List of Figures
#+TOC: figures
* Overview and Goals
** Document Structure
   This exporter is intended to provide a lot of flexibility through plain
   ConTeXt code with minimal elisp intervention. The output ConTeXt is
   structured to have as much setup code as possible in the document preamble
   and in general formatting instructions won't appear in the document body
   beyond simple semantic markers. In other words, unless you provide
   additional markup directives in the =org= file, there won't be any additional
   inline styling in the output ConTeXt file.
** Customization
   Customization can occur at three different levels of granularity. The
   coarsest control is the /preset/ which is set by the ~#+CONTEXT_PRESET~
   directive and is most similar to the LaTeX class. The next level of control
   is with /snippets/ which are predefined pieces of code that the user can
   define. For instance, the user can select just the ~layout-article~ snippet
   to select a page layout similar to the default LaTeX article. The lowest
   level of control is provided by inserting literal ConTeXt code directly into
   the document using ~#+CONTEXT_HEADER~, ~#+CONTEXT_HEADER_EXTRA~, and
   ~#+CONTEXT~ directives.

   Additional configuration can be inserted into the document preamble by using
   preset, snippet, or literal directives to customize the display of any of the
   different elements of the document.
** Compatibility
   This exporter is intended to provide as much compatibility as is reasonable
   with options and configuration for the LaTeX exporter.

* Features
  #+INCLUDE: "./examples/demo.org" 
