# Copyright (C) 2021 Jason Ross
# Author: Jason Ross <jasonross1024 at gmail dot com>

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
 

#+TITLE: Org Mode ConTeXt Export Demo
#+DESCRIPTION: Simple demo of the Org Mode ConTeXt exporter
#+AUTHOR: Jason Ross
#+EMAIL: jasonross1024@gmail.com
#+OPTIONS: toc:nil num:t
#+CONTEXT_HEADER: \usemodule[pret-python]

#+CONTEXT_HEADER_EXTRA: \setuppapersize[letter]
#+CONTEXT_HEADER_EXTRA: \setuplayout[backspace=1.85in, width=4.8in, height=7.64in]
#+CONTEXT_HEADER_EXTRA: \setupxtable [align=center, leftframe=off, rightframe=off, topframe=off,
#+CONTEXT_HEADER_EXTRA: bottomframe=off, loffset=1em, roffset=1em, stretch=on]
#+CONTEXT_HEADER_EXTRA: \setupxtable[orgheader][toffset=1ex, foregroundstyle=bold, bottomframe=on]
#+CONTEXT_HEADER_EXTRA: \setuptyping[orgblksrc]
#+CONTEXT_HEADER_EXTRA:    [before={\startframedtext[width=\makeupwidth,
#+CONTEXT_HEADER_EXTRA:                              background=color,
#+CONTEXT_HEADER_EXTRA:                              backgroundcolor=lightgray]},
#+CONTEXT_HEADER_EXTRA:     after={\stopframedtext},
#+CONTEXT_HEADER_EXTRA:     style={\small\tt},
#+CONTEXT_HEADER_EXTRA:     numbering=line]
#+CONTEXT_HEADER_EXTRA: \setupheadertexts[{\getvariable{org}{author}}][{\getvariable{org}{title}}]
#+CONTEXT_HEADER_EXTRA: \setupfootertexts[][{Page \pagenumber}]
#+CONTEXT_HEADER_EXTRA: \setuppagenumbering[location=]
#+CONTEXT_HEADER_EXTRA: \setuplinenumbering[style={\small\tt}]
#+CONTEXT_HEADER_EXTRA: \setupframedtext
#+CONTEXT_HEADER_EXTRA:   [orgblockquote]
#+CONTEXT_HEADER_EXTRA:   [style={\sl}, frame=off, location=middle]
#+DATE: 2021-01-07

* Problem 1
  - Problem :: Evaluate numerically the integral

  \[
  I = \int_0^{\pi/2}{\ln\left(\sin{x}\right) dx}
  \]

  and compare with the exact value $I = -\frac{\pi}{2}\ln{2}$

  - Solution :: ...

    Note that $\ln{\left(\sin x\right)} = \ln{\left(x \frac{\sin x}{x}\right)}
    = \ln{x} + \ln{\frac{\sin x}{x}}$

    Therefore we just need to find
    $\int_0^{\pi/2}{\ln{x} dx}$ analytically and evaluate
    $\int_0^{\pi/2}{\ln{\frac{\sin x}{x}} dx}$ numerically.

    $\int_0^{\pi/2}{\ln{x} dx}$ can be integrated by parts.

    Let $u = \ln x, v^{'} = dx, u^{'} = \frac{1}{x}, v = x$. Therefore,
    $$\int{ln{x} dx} = \int{u v^{'} dx} = u v - \int{v u^{'} dx}$$
    $$ u v - \int{v u^{'} dx} = x \ln x - \int{x \frac{1}{x} dx} = x \ln x - x$$
    And so, $\int_0^{\pi/2}{\ln x dx} = \left. x \ln x - x \right|_0^{\pi/2}$

    \begin{align*}
    \frac{d^4}{dx^4} e^{a x} + e^{a x} &= 0 \\
    a^4 e^{a x} + e^{a x} &= 0 \\
    a^4 + 1 &= 0 \\
    a^4 &= -1 \\
    \end{align*}

    And, $\int_0^{\pi/2}{\ln x dx} = \frac{pi}{2} \left(\ln x - 1\right) \approx -0.861$

    #+BEGIN_SRC python :results output code :exports both
    from sympy import log, pi, integrate
    from sympy.abc import x
    print((pi/2 * (log(pi/2) - 1)).evalf())
    print(integrate(log(x), (x, 0, pi/2)).evalf())
    #+END_SRC

    #+RESULTS:
    #+begin_src python
    -0.861451872082119
    -0.861451872082119
    #+end_src

    So we have a value for part of our problem. The other part is to evaluate the integral
    $$\int_0^{\pi/2}{\ln{\frac{\sin x}{x}} dx}$$
    We can do this with Simpson's rule. Recall that
    \[S = \frac{H}{9}\sum_{i=0}^{n-1}{f(x_0 + i H)+
    4 f\left(x_0 + \left(i + \frac{1}{2}\right) H\right) +
    f\left(x_0 + \left(i + 1\right) H\right)}\]
    
    #+begin_src python :results file :exports both
      import matplotlib.pyplot as plt
      import numpy as np
      x, y = np.meshgrid(np.linspace(0, 1, 25), np.linspace(0, 1, 25))
      def slope(x, y):
          return x - y**2
      u = np.ones_like(x)
      v = slope(x, y)
      plt.figure(figsize=(8, 8))
      plt.quiver(x, y, u, v, scale=30)
      plt.gcf().tight_layout()
      plt.plot(
          np.linspace(0, 1, 11),
          [0.000, 0.005, 0.020, 0.045, 0.080, 0.124,
           0.177, 0.238, 0.306, 0.380, 0.458]
      )
      plt.savefig("temp.pdf")
      return "temp.pdf"

    #+end_src

    #+CAPTION: Quiver Plot
    #+results:
    [[file:temp.pdf]]

** Sample Subheading
   - Item
     
     Some prose
   - Item 2

     Some more prose

   Here's some prose in the middle

   1. Numbered item
      - A subitem
        - A subsubitem
   2. Another numbered item

   *Here's some bold* /here's some italics/ +Here's some strikethrough+
   ~here's some code~ =here's some verbatim= _here's some underline!?_
   _/Here's some underlined italics/_


  
:TestDrawer:
Here's some junk in a drawer
:END:
 
   #+BEGIN_SRC lua
     local function s(a)
       if control[s] then
         foo(s)
       end
     end
   #+END_SRC

   #+BEGIN_SRC metapost
     beginfig(1)
       draw fullcircle scaled 3cm ;
     endfig ;
     end ;
   #+END_SRC
 

   Here's a link to [[Problem 1]]

   Here's a link to [[http://google.com][google]]

   Here's a bare link to https://orgmode.org
   
   #+BEGIN_EXPORT context
   \pagebreak
   \input{knuth}
   \pagebreak
   #+END_EXPORT
   

*** DONE Sample SubSubHeading                                     :sampletag:
    CLOSED: [2021-01-08 Fri 09:33]

    Here's a quote from Donald Knuth:
    #+BEGIN_QUOTE
    The best programs are written so that computing machines can perform them
    quickly and so that human beings can understand them clearly. A programmer
    is ideally an essayist who works with traditional aesthetic and literary
    forms as well as mathematical concepts, to communicate the way that an
    algorithm works and to convince a reader that the results will be correct.
    #+END_QUOTE
    -----
    
   #+BEGIN_EXPORT context
   \pagebreak
   #+END_EXPORT
**** Sample SubSubSubHeading

     Here's a table

     | Head 1 | Head 2 |
     |--------+--------|
     | Row 1  | Row 2  |

     That was the table

***** Sample SubSubSubSubHeading

****** Sample SubSubSubSubSubHeading
