#+OPTIONS: syntax:vim
* TODO Named URL
 Here's a link to [[https://orgmode.org][Org Mode]]
* Heading Link
  Here's a link to [[Named URL]]
* Anonymous url
  Here's a link to [[https://orgmode.org]]
* Anonymous Unmarked url
  https://orgmode.org
* Figure References
  <<Simple Target>>
  #+CAPTION: This is my figure
  #+NAME: MyFig
  [[./bessel11.pdf]]
  
  Here's a reference to [[MyFig][My Figure]] by a local name
  
  Here's a reference to Figure [[MyFig]] by number

* Section Heading 1

  Here's a reference to section [[Section Heading 1]] by number

  Here's a reference to [[Section Heading 1][The current section]] by a local name


  #+NAME: MyTab
  #+CAPTION: This is my table
  | H1 | H2 |
  | R1 | R2 |
  
  Here's a reference to table [[MyTab]] by number
  
  Here's a reference to the [[MyTab][above table]] by a local name

* Radio Targets
  
  This is a <<<sample radio target>>>

  and this is a link to a sample radio target

** Targetted section
    This is a link to [[Simple Target]]

    This is a link to [[Simple Target][simple target by another name]]

* Verse Blocks
  #+NAME: MyVerse
  #+BEGIN_VERSE
Phasellus at dui in ligula mollis ultricies.  
Donec at pede.  
Etiam vel neque nec dui dignissim bibendum.  
Sed diam.  
Nunc rutrum turpis sed pede.  
Nam a sapien.  
  #+END_VERSE

  This is a named reference to [[MyVerse][this verse block]]

  This is an anonymous reference to [[MyVerse]]

  
* Example Blocks
  #+NAME: MyExample
  #+BEGIN_EXAMPLE
var beer = 99;
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_EXAMPLE

  This is a named reference to [[MyExample][this example]]

  This is an anonymous reference to [[MyExample]]

* Code Blocks
  #+NAME: MyCode
  #+BEGIN_SRC javascript
var beer = 99;
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_SRC

  This is a named reference to [[MyCode][this code block]]

  This is a numbered reference to listing [[MyCode]]

  #+NAME: MyNumberedCode
  #+BEGIN_SRC javascript -n
var beer = 99;       (ref:TestRef1)
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_SRC

  This should be a link to TestRef1 of the above block.

  Here's a link to [[(TestRef1)]]


  #+NAME: MyNumberedCode2
  #+BEGIN_SRC javascript -n -r
var beer = 99;       (ref:TestRef2)
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_SRC

  This should be a link to line 1 of the above block.

  Here's a link to [[(TestRef2)]]

  #+NAME: MyNumberedCode2
  #+BEGIN_SRC javascript -r
var beer = 99;       (ref:TestRef3)
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_SRC

  This should be a link to line 1

  Here's a link to [[(TestRef3)]]

  #+NAME: MyNumberedCode2
  #+BEGIN_SRC javascript
var beer = 99;       (ref:TestRef4)
while (beer > 0) {
    var verse = [
        beer + " bottles of beer on the wall,",
        beer + " bottles of beer!",
        "Take one down, pass it around",
        (beer - 1) + " bottles of beer on the wall!"
    ].join("\n");

    console.log(verse);

    beer--;
}
  #+END_SRC

  This should be a link to TestRef4

  Here's a link to [[(TestRef4)]]

  #+BEGIN_EXAMPLE python
  import this    (ref:TestRef5)
  def foo(bar):
     for i in range(5):
        print(i**2)
  #+END_EXAMPLE

  This should be a link to line 1

  Here's a link to line [[(TestRef5)]]

  #+BEGIN_EXAMPLE python -n
  import this    (ref:TestRef6)
  def foo(bar):
     for i in range(5):
        print(i**2)
  #+END_EXAMPLE

  This should be a link to line 1

  Here's a link to [[(TestRef6)]]

  #+BEGIN_EXAMPLE python -r
  import this    (ref:TestRef7)
  def foo(bar):
     for i in range(5):
        print(i**2)
  #+END_EXAMPLE

  This should be a link to TestRef7

  Here's a link to [[(TestRef7)]]


  #+BEGIN_EXAMPLE python -r -n
  import this    (ref:TestRef8)
  def foo(bar):
     for i in range(5):
        print(i**2)
  #+END_EXAMPLE

  This should be a link to TestRef8

  Here's a link to [[(TestRef8)]]
* Equations

#+CAPTION: A labelled linked euqation
#+NAME: labeled-eq
\begin{align}
\frac{d^4}{dx^4} e^{a x} + e^{a x} &= 0 \\
a^4 e^{a x} + e^{a x} &= 0 \\
a^4 + 1 &= 0 \\
a^4 &= -1 \\
\end{align}

[[labeled-eq][Here's a link to an equation]]

Here's a link to equation [[labeled-eq]]

